Repository SSU-RETURN/emuda-back, pull requests merged in 2024-05, with the labels that each got.

#27 :sparkles: [feat]: 회원가입 API 구현
  build.gradle
  src/main/java/com/app/demo/controller/MemberController.java
  src/main/java/com/app/demo/dto/MemberSignupDTO.java
  src/main/java/com/app/demo/entity/Member.java
  src/main/java/com/app/demo/repository/MemberRepository.java
  src/main/java/com/app/demo/service/MemberService.java
  src/main/java/com/app/demo/service/impl/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#31 ✨ [feat]: 취향 API 구현
  src/main/java/com/app/demo/controller/MemberPreferenceController.java
  src/main/java/com/app/demo/converter/MemberPreferenceConverter.java
  src/main/java/com/app/demo/dto/request/MemberPreferenceRequestDTO.java
  src/main/java/com/app/demo/dto/response/MemberPreferenceResponseDTO.java
  src/main/java/com/app/demo/entity/MemberPreference.java
  src/main/java/com/app/demo/entity/enums/Genre.java
  src/main/java/com/app/demo/repository/MemberPreferenceRepository.java
  src/main/java/com/app/demo/service/MemberPreferenceService.java
  src/main/java/com/app/demo/service/impl/MemberPreferenceServiceImpl.java
Labels: :sparkles: feature

#33 :sparkles: [feat]: 로그인 api 구현
  src/main/java/com/app/demo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/app/demo/config/SecurityConfig.java
  src/main/java/com/app/demo/config/SwaggerConfig.java
  src/main/java/com/app/demo/config/WebConfig.java
  src/main/java/com/app/demo/controller/MemberController.java
  src/main/java/com/app/demo/controller/MusicController.java
  src/main/java/com/app/demo/converter/MemberConverter.java
  src/main/java/com/app/demo/dto/request/LoginRequestDTO.java
  src/main/java/com/app/demo/dto/response/LoginResponseDTO.java
  src/main/java/com/app/demo/dto/response/TokenRefreshResponse.java
  src/main/java/com/app/demo/security/filter/AuthExceptionHandlingFilter.java
  src/main/java/com/app/demo/security/filter/JwtRequestFilter.java
  src/main/java/com/app/demo/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/app/demo/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/app/demo/security/handler/annotation/ExtractToken.java
  src/main/java/com/app/demo/security/handler/resolver/ExtractTokenArgumentResolver.java
  src/main/java/com/app/demo/security/principal/PrincipalDetails.java
  src/main/java/com/app/demo/security/principal/PrincipalDetailsService.java
  src/main/java/com/app/demo/security/provider/JwtTokenProvider.java
  src/main/java/com/app/demo/service/MemberService.java
  src/main/java/com/app/demo/service/impl/MemberServiceImpl.java
  src/main/resources/application-jwt.yml
Labels: :sparkles: feature

#37 :sparkles: [feat]: 회원 탈퇴 API 구현
  .gitignore
  src/main/java/com/app/demo/controller/MemberController.java
  src/main/java/com/app/demo/entity/Diary.java
  src/main/java/com/app/demo/entity/Member.java
  src/main/java/com/app/demo/entity/PreferencePlaylist.java
  src/main/java/com/app/demo/entity/mapping/AIPlaylistMusic.java
  src/main/java/com/app/demo/entity/mapping/MemberPlaylistMusic.java
  src/main/java/com/app/demo/service/DiaryService.java
  src/main/java/com/app/demo/service/MemberService.java
  src/main/java/com/app/demo/service/impl/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#35 ✨ [feat]: getPlaylist API 구현
  src/main/java/com/app/demo/controller/AIPlaylistController.java
  src/main/java/com/app/demo/controller/DiaryController.java
  src/main/java/com/app/demo/controller/MemberPlaylistController.java
  src/main/java/com/app/demo/controller/MemberPreferenceController.java
  src/main/java/com/app/demo/converter/AIPlaylistConverter.java
  src/main/java/com/app/demo/converter/DiaryConverter.java
  src/main/java/com/app/demo/converter/MemberPlaylistConverter.java
  src/main/java/com/app/demo/converter/MemberPlaylistInfoConverter.java
  src/main/java/com/app/demo/dto/response/AIPlaylistResponseDTO.java
  src/main/java/com/app/demo/dto/response/MemberPlaylistResponseDTO.java
  src/main/java/com/app/demo/entity/AIPlaylist.java
  src/main/java/com/app/demo/entity/Diary.java
  src/main/java/com/app/demo/entity/MemberPlaylist.java
  src/main/java/com/app/demo/entity/MemberPreferencePlaylist.java
  src/main/java/com/app/demo/entity/mapping/AIPlaylistMusic.java
  src/main/java/com/app/demo/entity/mapping/MemberPlaylistMusic.java
  src/main/java/com/app/demo/repository/AIPlaylistMusicRepository.java
  src/main/java/com/app/demo/repository/AIPlaylistRepository.java
  src/main/java/com/app/demo/repository/DiaryRepository.java
  src/main/java/com/app/demo/repository/MemberPlaylistMusicRepository.java
  src/main/java/com/app/demo/repository/MemberPlaylistRepository.java
  src/main/java/com/app/demo/service/AIPlaylistService.java
  src/main/java/com/app/demo/service/MemberPlaylistService.java
  src/main/java/com/app/demo/service/impl/AIPlaylistServiceImpl.java
  src/main/java/com/app/demo/service/impl/DiaryServiceImpl.java
  src/main/java/com/app/demo/service/impl/MemberPlaylistServiceImpl.java
Labels: :sparkles: feature

#41 :axe:[Fix]: DiaryAPI수정
  src/main/java/com/app/demo/converter/DiaryConverter.java
  src/main/java/com/app/demo/dto/request/DiaryRequestDTO.java
  src/main/java/com/app/demo/dto/response/AIPlaylistResponseDTO.java
  src/main/java/com/app/demo/dto/response/DiaryResponseDTO.java
  src/main/java/com/app/demo/entity/AIPlaylist.java
  src/main/java/com/app/demo/entity/Diary.java
  src/main/java/com/app/demo/service/impl/DiaryServiceImpl.java
Labels: :axe: Fix

#44 :star2: [update]: url 수정 등
  src/main/java/com/app/demo/controller/AIPlaylistController.java
  src/main/java/com/app/demo/controller/DiaryController.java
  src/main/java/com/app/demo/controller/MemberPlaylistController.java
  src/main/java/com/app/demo/controller/MemberPreferenceController.java
  src/main/java/com/app/demo/converter/DiaryConverter.java
  src/main/java/com/app/demo/dto/response/DiaryResponseDTO.java
  src/main/java/com/app/demo/entity/Music.java
  src/main/java/com/app/demo/entity/PreferencePlaylist.java
  src/main/java/com/app/demo/entity/mapping/MemberPreferencePlaylistMusic.java
Labels: :star2: update

#46 🪓[Fix]: build 오류 해결
  src/main/java/com/app/demo/converter/DiaryConverter.java
  src/main/java/com/app/demo/entity/AiEmotion.java
  src/main/java/com/app/demo/entity/Diary.java
  src/main/java/com/app/demo/service/impl/DiaryServiceImpl.java
Labels: :axe: Fix

#47 🌟 [Update]: develop branch수정 내용 memberPreferencePlaylist에 적용
  src/main/java/com/app/demo/controller/AIPlaylistController.java
  src/main/java/com/app/demo/controller/DiaryController.java
  src/main/java/com/app/demo/controller/MemberPlaylistController.java
  src/main/java/com/app/demo/controller/MemberPreferenceController.java
  src/main/java/com/app/demo/converter/DiaryConverter.java
  src/main/java/com/app/demo/dto/request/DiaryRequestDTO.java
  src/main/java/com/app/demo/dto/response/AIPlaylistResponseDTO.java
  src/main/java/com/app/demo/dto/response/DiaryResponseDTO.java
  src/main/java/com/app/demo/entity/AIPlaylist.java
  src/main/java/com/app/demo/entity/AiEmotion.java
  src/main/java/com/app/demo/entity/Diary.java
  src/main/java/com/app/demo/entity/Music.java
  src/main/java/com/app/demo/entity/PreferencePlaylist.java
  src/main/java/com/app/demo/entity/mapping/MemberPreferencePlaylistMusic.java
  src/main/java/com/app/demo/service/impl/DiaryServiceImpl.java
Labels: :star2: update

#49 :axe:[Fix]: Preference 오타 수정
  src/main/java/com/app/demo/entity/enums/Preference.java
Labels: :axe: Fix

#51 :star2: [update]: 취향 조회 api
  src/main/java/com/app/demo/controller/MemberPreferenceController.java
Labels: :star2: update

#54 :axe:[Fix]: MemberPreferenceAPI 수정
  src/main/java/com/app/demo/controller/MemberPreferenceController.java
  src/main/java/com/app/demo/repository/MemberPreferenceRepository.java
  src/main/java/com/app/demo/service/MemberPreferenceService.java
  src/main/java/com/app/demo/service/impl/MemberPreferenceServiceImpl.java
Labels: :axe: Fix

#55 :axe:[Fix]: UpdatePreference수정
  src/main/java/com/app/demo/service/impl/MemberPreferenceServiceImpl.java
Labels: :axe: Fix

#58 :sparkles: [Feat]: UpdatePasswd, UpdateNickname API제작
  src/main/java/com/app/demo/controller/MemberController.java
  src/main/java/com/app/demo/dto/request/MemberRequestDTO.java
  src/main/java/com/app/demo/service/MemberService.java
  src/main/java/com/app/demo/service/impl/MemberServiceImpl.java
Labels: :sparkles: feature

#57 ✨ [feat]: 일기 저장 api 구현
  build.gradle
  src/main/java/com/app/demo/config/S3Config.java
  src/main/java/com/app/demo/controller/DiaryController.java
  src/main/java/com/app/demo/controller/MemberPlaylistController.java
  src/main/java/com/app/demo/converter/AIPlaylistConverter.java
  src/main/java/com/app/demo/converter/MemberPlaylistConverter.java
  src/main/java/com/app/demo/converter/MemberPreferenceConverter.java
  src/main/java/com/app/demo/converter/MusicConverter.java
  src/main/java/com/app/demo/dto/request/DiaryRequestDTO.java
  src/main/java/com/app/demo/dto/request/MemberPreferenceRequestDTO.java
  src/main/java/com/app/demo/dto/request/MusicRequestDTO.java
  src/main/java/com/app/demo/dto/response/AiEmotionResponse.java
  src/main/java/com/app/demo/entity/AIPlaylist.java
  src/main/java/com/app/demo/entity/AiEmotion.java
  src/main/java/com/app/demo/entity/Diary.java
  src/main/java/com/app/demo/entity/MemberPlaylist.java
  src/main/java/com/app/demo/entity/MemberPreference.java
  src/main/java/com/app/demo/entity/enums/Genre.java
  src/main/java/com/app/demo/entity/mapping/AIPlaylistMusic.java
  src/main/java/com/app/demo/entity/mapping/MemberPlaylistMusic.java
  src/main/java/com/app/demo/repository/AIPlaylistMusicRepository.java
  src/main/java/com/app/demo/repository/AIPlaylistRepository.java
  src/main/java/com/app/demo/repository/AiEmotionRepository.java
  src/main/java/com/app/demo/repository/MemberPlaylistRepository.java
  src/main/java/com/app/demo/repository/MusicRepository.java
  src/main/java/com/app/demo/service/AIPlaylistService.java
  src/main/java/com/app/demo/service/AiEmotionService.java
  src/main/java/com/app/demo/service/AiPlaylistMusicService.java
  src/main/java/com/app/demo/service/ChatGPTService.java
  src/main/java/com/app/demo/service/MemberPlaylistMusicService.java
  src/main/java/com/app/demo/service/MemberPlaylistService.java
  src/main/java/com/app/demo/service/MemberPreferenceService.java
  src/main/java/com/app/demo/service/chatgpt/ChatGPTAPI.java
  src/main/java/com/app/demo/service/impl/AIPlaylistServiceImpl.java
  src/main/java/com/app/demo/service/impl/AiEmotionServiceImpl.java
  src/main/java/com/app/demo/service/impl/AiPlaylistMusicServiceImpl.java
  src/main/java/com/app/demo/service/impl/ChatGPTServiceImpl.java
  src/main/java/com/app/demo/service/impl/DiaryServiceImpl.java
  src/main/java/com/app/demo/service/impl/MemberPlaylistMusicServiceImpl.java
  src/main/java/com/app/demo/service/impl/MemberPlaylistServiceImpl.java
  src/main/java/com/app/demo/service/impl/MemberPreferenceServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#61 :sparkles: [feat]: 감정분석 결과 조회 api 구현
  src/main/java/com/app/demo/config/S3Config.java
  src/main/java/com/app/demo/controller/DiaryController.java
  src/main/java/com/app/demo/converter/DiaryConverter.java
  src/main/java/com/app/demo/dto/response/DiaryResponseDTO.java
  src/main/java/com/app/demo/service/DiaryService.java
  src/main/java/com/app/demo/service/impl/AiEmotionServiceImpl.java
  src/main/java/com/app/demo/service/impl/DiaryServiceImpl.java
Labels: :sparkles: feature

#64 🪓 [fix]: DB 관련 오류 해결
  src/main/java/com/app/demo/converter/MemberPlaylistConverter.java
  src/main/java/com/app/demo/entity/mapping/MemberPlaylistMusic.java
  src/main/java/com/app/demo/repository/MemberPlaylistMusicRepository.java
  src/main/java/com/app/demo/repository/MemberPlaylistRepository.java
  src/main/java/com/app/demo/service/impl/MemberPlaylistServiceImpl.java
Labels: :axe: Fix

#67 :star2: [update]: 일기 생성 수정 및 s3 설정 수정
  src/main/java/com/app/demo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/app/demo/config/WebConfig.java
  src/main/java/com/app/demo/controller/DiaryController.java
  src/main/java/com/app/demo/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/app/demo/dto/request/DiaryRequestDTO.java
  src/main/java/com/app/demo/service/DiaryService.java
  src/main/java/com/app/demo/service/S3ImageService.java
  src/main/java/com/app/demo/service/impl/AiEmotionServiceImpl.java
  src/main/java/com/app/demo/service/impl/ChatGPTServiceImpl.java
  src/main/java/com/app/demo/service/impl/DiaryServiceImpl.java
  src/main/java/com/app/demo/service/impl/S3ImageServiceImpl.java
  src/main/resources/application-s3.yml
Labels: :star2: update

#66 :axe:[Fix]: Preference playlist api수
  src/main/java/com/app/demo/controller/MemberPreferencePlaylistController.java
  src/main/java/com/app/demo/converter/MemberPreferencePlaylistConverter.java
  src/main/java/com/app/demo/converter/MemberPreferencePlaylistMusicsConverter.java
  src/main/java/com/app/demo/dto/request/MemberPreferencePlaylistRequestDTO.java
  src/main/java/com/app/demo/dto/response/MemberPreferencePlaylistResponseDTO.java
  src/main/java/com/app/demo/entity/Member.java
  src/main/java/com/app/demo/entity/MemberPreferencePlaylist.java
  src/main/java/com/app/demo/entity/mapping/MemberPreferencePlaylistMusic.java
  src/main/java/com/app/demo/repository/MemberPreferencePlaylistMusicRepository.java
  src/main/java/com/app/demo/repository/MemberPreferencePlaylistRepository.java
  src/main/java/com/app/demo/service/ChatGPTService.java
  src/main/java/com/app/demo/service/MemberPreferencePlaylistService.java
  src/main/java/com/app/demo/service/impl/ChatGPTServiceImpl.java
  src/main/java/com/app/demo/service/impl/MemberPreferencePlaylistServiceImpl.java
Labels: :axe: Fix, :star2: update

#70 🌟 [update]: memberPlaylist 가져오기 + 페이징 처리
  src/main/java/com/app/demo/controller/MemberPlaylistController.java
  src/main/java/com/app/demo/converter/MemberPlaylistConverter.java
  src/main/java/com/app/demo/dto/response/MemberPlaylistResponseDTO.java
  src/main/java/com/app/demo/entity/enums/Emotion.java
  src/main/java/com/app/demo/repository/MemberPlaylistMusicRepository.java
  src/main/java/com/app/demo/repository/MemberPlaylistRepository.java
  src/main/java/com/app/demo/service/MemberPlaylistService.java
  src/main/java/com/app/demo/service/impl/MemberPlaylistServiceImpl.java
Labels: :star2: update

#72 :star2: [update]: 로그인 취향존재여부 반환 추가
  src/main/java/com/app/demo/converter/MemberConverter.java
  src/main/java/com/app/demo/dto/response/LoginResponseDTO.java
  src/main/java/com/app/demo/service/impl/MemberServiceImpl.java
Labels: :star2: update

#75 :star2: [update]: ChatGPT 음악 반환 개수 수정
  src/main/java/com/app/demo/service/impl/ChatGPTServiceImpl.java
Labels: :star2: update

#80 :star2: [update]: 장르 추가
  src/main/java/com/app/demo/entity/enums/Genre.java
Labels: :star2: update

#82 :star2: [update]: 취향 저장 예외 처리
  src/main/java/com/app/demo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/app/demo/service/impl/MemberPreferenceServiceImpl.java
Labels: :star2: update

#85 :axe:[Fix]:deleteDiary API 수정
  src/main/java/com/app/demo/repository/AIPlaylistMusicRepository.java
  src/main/java/com/app/demo/repository/MemberPlaylistMusicRepository.java
  src/main/java/com/app/demo/repository/MemberPlaylistRepository.java
  src/main/java/com/app/demo/service/impl/DiaryServiceImpl.java
Labels: :axe: Fix

#88 :star2: [update]: surprise -> anxiety로 변경
  src/main/java/com/app/demo/converter/MemberPreferenceConverter.java
  src/main/java/com/app/demo/dto/request/MemberPreferenceRequestDTO.java
  src/main/java/com/app/demo/entity/MemberPreference.java
  src/main/java/com/app/demo/entity/enums/Emotion.java
  src/main/java/com/app/demo/service/impl/MemberPreferenceServiceImpl.java
Labels: :star2: update

#89 :sparkles:[Feat]: getTodayEmotionAPI
  src/main/java/com/app/demo/controller/DiaryController.java
  src/main/java/com/app/demo/converter/DiaryConverter.java
  src/main/java/com/app/demo/dto/response/DiaryResponseDTO.java
  src/main/java/com/app/demo/entity/Diary.java
  src/main/java/com/app/demo/service/DiaryService.java
  src/main/java/com/app/demo/service/impl/DiaryServiceImpl.java
Labels: :sparkles: feature

#91 :star2:[Update]: objectException
  src/main/java/com/app/demo/controller/DiaryController.java
  src/main/java/com/app/demo/controller/MemberPreferencePlaylistController.java
  src/main/java/com/app/demo/service/impl/DiaryServiceImpl.java
Labels: :star2: update

#93 :star2: [update]: 취향 플레이리스트 관련 예외 처리
  src/main/java/com/app/demo/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/app/demo/service/impl/MemberPreferencePlaylistServiceImpl.java
Labels: :star2: update
